name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: setting up
      run: |
        sudo apt update
        sudo apt install -y cmake
        sudo apt install -y git
        sudo apt install -y libgtest-dev
        sudo apt install -y lcov

    - name: testing
      run: |
        mkdir build
        cd build
        mkdir coverage
        touch coverage/lcov.info
        cmake ..
        make
        ./tests

    - name: coverage
      run: |
          lcov --capture --directory . -o ./lcov.info
          lcov --remove lcov.info '*/gtest/*' '/usr/*' -o lcov.info
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.0.0
      with:
        path-to-lcov: "./lcov.info"

